services:
  afcv3:
    container_name: afcv3-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      ONLYOFFICE_URL: http://DOMAIN_OR_IP:8081  # Da modificare con il dominio o IP del server
      UPLOADS_DIR: /var/www/onlyoffice/Data
    ports:
      - 3000:3000
    volumes:
      - ./uploads:/var/www/onlyoffice/Data
      - ./database:/usr/src/app/database
    depends_on:
      - onlyoffice-document-server
    restart: always

  onlyoffice-document-server:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice-document-server
    ports:
      - "8081:80"
    volumes:
      - ./uploads:/var/www/onlyoffice/Data
      - ./logs/onlyoffice:/var/log/onlyoffice
      - redis:/var/lib/redis
      - rabbitmq:/var/lib/rabbitmq
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=MDQ879SA5Lw8wnGxJ2TTPK5IFTIX2KZ7
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

volumes:
  redis:
  rabbitmq:
