version: "3.7"

services:
  afcv3:
    container_name: afcv3-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      SERVER_HOST: afcv3-backend        # <--- IMPORTANTE: usiamo il nome di rete Docker
      PORT: 3000
      ONLYOFFICE_URL: http://localhost:8081  # usato dal frontend/JS per caricare l'editor
      UPLOADS_DIR: /var/www/onlyoffice/Data
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/var/www/onlyoffice/Data
      - ./database:/usr/src/app/database
    depends_on:
      - onlyoffice-document-server
    restart: unless-stopped

  onlyoffice-document-server:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice-document-server
    ports:
      - "8081:80"  # Espone la porta 80 del container su 8081 dell'host
    volumes:
      - ./uploads:/var/www/onlyoffice/Data
      - logs:/var/log/onlyoffice
      - redis:/var/lib/redis
      - rabbitmq:/var/lib/rabbitmq
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=MDQ879SA5Lw8wnGxJ2TTPK5IFTIX2KZ7
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  logs:
  redis:
  rabbitmq:
